[versions]
projektor = "4.+"

kotlin = "2.0.21"

kotlin-utils = "0.8.9"
gradle-utils = "0.8.14"

kotlin-serialization-json = "1.7.3"

[plugins]
projektor = { id = "io.github.diskria.projektor", version.ref = "projektor" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
kotlin-utils = { group = "io.github.diskria", name = "kotlin-utils", version.ref = "kotlin-utils" }
gradle-utils = { group = "io.github.diskria", name = "gradle-utils", version.ref = "gradle-utils" }

kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json-jvm", version.ref = "kotlin-serialization-json" }

[bundles]
diskria-utils = [
    "kotlin-utils",
    "gradle-utils",
]
